import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";
import Hero from "../components/Hero";
import { api } from "~/utils/api";
import Features from "~/components/Features";
import ImageDescription from "~/components/ImageDescription";
import Footer from "~/components/Footer";
import FAQ from "~/components/FAQ";
import Navbar from "~/components/Navbar";
const FeatureData = [
  {
    title: "Diş Protezlerir",
    description:
      "Diş teknisyenleri, eksik dişleri yerine koymak için fonksiyonel ve estetik diş protezleri tasarlar ve üretir.",
    imgSrc: "images/Feature-Image/feature-1.svg", // public klasörü olmadan ve / işareti olmadan
  },
  {
    title: "İmplant Destekli Protezler",
    description:
      "Diş teknisyenleri, güvenilir ve doğal protezler üretir, çiğneme fonksiyonunu geri kazandırır.",
    imgSrc: "images/Feature-Image/feature-2.svg", // public klasörü olmadan ve / işareti olmadan
  },
  {
    title: "Porselen Diş Kaplamaları",
    description:
      "Diş teknisyenleri, porselen diş kaplamalarını özel olarak tasarlar ve üretir, hastaların estetik gülüşlerine katkı sağlar.",
    imgSrc: "images/Feature-Image/feature-3.svg", // public klasörü olmadan ve / işareti olmadan
  },
];
const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>gultekingulestan.com</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" flex flex-col gap-y-12">
        <Hero
          title="Kusursuz Gülüşler için Kusursuz Diş İmplantları"
          description="Gülümsemeniz İçin Hızlı ve Özgün Çözümleri Ekonomik ve Estetik Diş İmplantlarıyla Fark Yaratıyoruz"
          active={true}
        />
        <div className=" flex  flex-wrap items-center  justify-evenly gap-y-6  ">
          {FeatureData.map((data) => (
            <Features
              title={data.title}
              description={data.description}
              imgSrc={data.imgSrc}
            />
          ))}
        </div>
        <ImageDescription
          bg="bg-gray-100"
          title="Doğal ve Dayanıklı Diş İmplantlarıyla Sağlıklı Gülüşler"
          description="Gülümsemelerinizi mükemmelleştirin! Uzman ekibimiz, estetik ve dayanıklı diş implantlarıyla sağlıklı gülüşlere kavuşmanızı sağlar. Güvenilir çözümler için bizimle iletişime geçin."
        />
        <FAQ />
        <Footer />
      </main>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
      {sessionData && sessionData.user.email === "gulestanbekir@gmail.com" && (
        <Link
          className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
          href={"/dashboard"}
        >
          Admin Dashboard
        </Link>
      )}
    </div>
  );
};
